export const greenhouse = [
    {
        title: "title 1",
        imgSrc: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        price: Math.round(Math.random()*200),
        discount: 10,
        discountDeadline: new Date(2022, 2, 23),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis exercitationem culpa nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus asperiores quasi cupiditate. Voluptatum ducimus voluptates voluptas?",
        numReviews: Math.round(Math.random()*1000),
        aveReviews: Math.round(Math.random()*10),
        strain: "indica",
        imgSrc1: "/src/lib/assets/images/greenhouse/Frosted Apricots.jpg",
        imgSrc2: "/src/lib/assets/images/greenhouse/Lion's Bread.jpg",
        imgSrc3: "/src/lib/assets/images/greenhouse/Perps Express.jpg",
    },
    {
        title: "title 2",
        imgSrc: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        price: Math.round(Math.random()*200),
        discount: 10,
        discountDeadline: new Date(2022, 2, 1),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis exercitationem culpa nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus asperiores quasi cupiditate. Voluptatum ducimus voluptates voluptas?",
        numReviews: Math.round(Math.random()*1000),
        aveReviews: Math.round(Math.random()*10),
        strain: "indica",
        imgSrc1: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc2: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc3: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
    },
    {
        title: "Title 3",
        imgSrc: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        price: Math.round(Math.random()*200),
        discount: 10,
        discountDeadline: new Date(2022, 2, 26),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis exercitationem culpa nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus asperiores quasi cupiditate. Voluptatum ducimus voluptates voluptas?",
        numReviews: Math.round(Math.random()*1000),
        aveReviews: Math.round(Math.random()*10),
        strain: "indica",
        imgSrc1: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc2: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc3: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
    },
    {
        title: "Title 4",
        imgSrc: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        price: Math.round(Math.random()*200),
        discount: 10,
        discountDeadline: new Date(2022, 2, 20),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis exercitationem culpa nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus asperiores quasi cupiditate. Voluptatum ducimus voluptates voluptas?",
        numReviews: Math.round(Math.random()*1000),
        aveReviews: Math.round(Math.random()*10),
        strain: "indica",
        imgSrc1: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc2: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc3: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
    },
    {
        title: "Title 5",
        imgSrc: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        price: Math.round(Math.random()*200),
        discount: 10,
        discountDeadline: new Date(2022, 2, 20),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis exercitationem culpa nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus asperiores quasi cupiditate. Voluptatum ducimus voluptates voluptas?",
        numReviews: Math.round(Math.random()*1000),
        aveReviews: Math.round(Math.random()*10),
        strain: "sativa",
        imgSrc1: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc2: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc3: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
    },
    {
        title: "Title 6",
        imgSrc: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        price: Math.round(Math.random()*200),
        discount: 10,
        discountDeadline: new Date(2022, 2, 20),
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis exercitationem culpa nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus asperiores quasi cupiditate. Voluptatum ducimus voluptates voluptas?",
        numReviews: Math.round(Math.random()*1000),
        aveReviews: Math.round(Math.random()*10),
        strain: "sativa",
        imgSrc1: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc2: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
        imgSrc3: "/src/lib/assets/images/greenhouse/Blunicorn.jpg",
    },
]